title: "Owens Tech Support and Web Development"
author: "AJ Owens"
description: "Owens Tech Support and Web Development"
permalink: /title:/ 
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:               
  - {file: "index.html", title: "Home", icon: home}
  - {file: "README.md", title: "About Me", icon: address-card}
  - {title: "Blog", file: "/blog.md"}

external:                  # see http://fontawesome.com/icons
  - {title: "Mail", icon: envelope, url: "mailto:owensdevelopment6@gmail.com"}
  - {title: "Github", icon: github, url: "https://github.com/ajowens1986"}
  - {title: "facebook", icon: facebook, url: "https:facebook.com/ashton.owens/"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
